---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flamingo-demo
  namespace: flux-system
spec:
  interval: 30s
  url: oci://ghcr.io/herveleclerc/manifests/argocd
  ref:
    tag: 1.0.1

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flamingo-demo
  namespace: flux-system
spec:
  targetNamespace: argocd
  prune: true
  interval: 2m
  path: "./init"
  sourceRef:
    kind: OCIRepository
    name: flamingo-demo
    namespace: flux-system
  timeout: 3m

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-demo
  namespace: flux-system
spec:
  targetNamespace: podinfo
  prune: true
  interval: 2m
  path: "./podinfo"
  sourceRef:
    kind: OCIRepository
    name: flamingo-demo
    namespace: flux-system
  timeout: 3m
